//  types of actions
export const FETCH_ADS_REQUEST = 'FETCH_ADS_REQUEST';
export const FETCH_ADS_SUCCESS = 'FETCH_ADS_SUCCESS';
export const FETCH_ADS_FAILURE = 'FETCH_ADS_FAILURE';
export const RECORD_CONVERSIONS_SUCCESS = 'RECORD_CONVERSIONS_SUCCESS';
export const RECORD_CONVERSIONS_FAILURE = 'RECORD_CONVERSIONS_FAILURE';

